services:
  client:
    container_name: client
    ports:
      - "3000:80"
    build:
      context: ./client
      dockerfile: Dockerfile

  nginx:
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./nginx/dev/nginx.conf.dev.template:/etc/nginx/nginx.conf.template
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    build:
      context: .
      dockerfile: ./nginx/dev/Dockerfile.dev
    restart: always
    depends_on:
      - client

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
