services:
  client:
    container_name: client
    ports:
      - "3000:80"
    build:
      context: ./client
      dockerfile: Dockerfile

  nginx:
    container_name: nginx
    # tty: true
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./nginx/cert.pem:/etc/cert.pem
      - ./nginx/key.pem:/etc/key.pem
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: always
    depends_on:
      - client

  certbot:
    container_name: certbot
    ports:
      - "6000:80"
    env_file:
      - .env
    # и снова мониторуем директорию nginx
    volumes:
      - ./nginx/:/etc/nginx/
    build:
      context: ./certbot
      dockerfile: Dockerfile
      # задаем переменные среды
      args:
        DOMAIN_EMAIL: ${DOMAIN_EMAIL}
        DOMAIN_URL: ${DOMAIN_URL}