server {
  listen 80 default_server;

  server_name ${NGINX_HOST};

  location / {
    root /usr/share/nginx/html/client;
    index index.html index.htm;
    try_files $uri $uri/ /index.html =404;
  }
}